// Generated by CoffeeScript 1.9.2
(function() {
  angular.module('metaEditor', ['ngResource', 'ngMessages', 'ngRoute', 'mgcrea.ngStrap', 'ui.bootstrap']).config([
    '$locationProvider', '$routeProvider', '$httpProvider', function($locationProvider, $routeProvider, $httpProvider) {
      var baseUrl;
      $locationProvider.html5Mode(true);
      $httpProvider.interceptors.push("AuthInterceptor");
      if (window.location.hostname.indexOf(".dev") > -1) {
        baseUrl = "";
      } else {
        baseUrl = "/meta-editor";
      }
      return $routeProvider.when(baseUrl + '/', {
        templateUrl: 'views/login.html',
        guestView: true,
        controller: 'LoginCtrl'
      }).when(baseUrl + '/reports-view', {
        templateUrl: 'views/reports.html',
        guestView: true,
        controller: 'ReportCtrl'
      }).when(baseUrl + '/:court', {
        guestView: false,
        templateUrl: 'views/legal-heads.html',
        controller: 'LegalHeadsCtrl'
      }).when(baseUrl + '/:court/:legal_head', {
        guestView: false,
        templateUrl: 'views/subject-matters.html',
        controller: 'LegalHeadCtrl'
      }).when(baseUrl + '/:court/:legal_head/:subject', {
        guestView: false,
        templateUrl: 'views/issues.html',
        controller: 'IssuesCtrl'
      }).otherwise({
        redirectTo: baseUrl + '/sc'
      });
    }
  ]).run([
    '$rootScope', 'AuthEvents', 'AuthService', 'AppConstants', '$location', function($rootScope, AuthEvents, AuthService, AppConstants, $location) {
      var toLogin;
      $rootScope.$on(AuthEvents.notAuthenticated, function() {
        return toLogin();
      });
      $rootScope.$on(AuthEvents.sessionTimeout, function() {
        alert(AuthEvents.sessionTimeout);
        return toLogin("Your Session has timed out");
      });
      $rootScope.$on(AuthEvents.loginFailed, function() {
        return alert("Login Failed");
      });
      $rootScope.$on('$routeChangeStart', function(event, next) {
        if (AuthService.isGuest() && !next.guestView) {
          return $rootScope.$broadcast(AuthEvents.notAuthenticated);
        }
      });
      return toLogin = function() {
        return $location.path("/");
      };
    }
  ]).constant("CONF", {
    countHeader: "ME-Count",
    pageHeader: "ME-Page"
  });

  String.prototype.hexEncode = function() {
    var hex, i, k, ref, result;
    result = "";
    for (i = k = 0, ref = this.length - 1; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
      hex = this.charCodeAt(i).toString(16);
      result += ("000" + hex).slice(-4);
    }
    return result;
  };

  String.prototype.hexDecode = function() {
    var back, hexes, j, k, ref;
    hexes = this.match(/.{1,4}/g) || [];
    back = "";
    for (j = k = 0, ref = hexes.length - 1; 0 <= ref ? k <= ref : k >= ref; j = 0 <= ref ? ++k : --k) {
      back += String.fromCharCode(parseInt(hexes[j], 16));
    }
    return back;
  };

}).call(this);
