// Generated by CoffeeScript 1.9.2
(function() {
  angular.module('metaEditor').controller('NavbarCtrl', [
    '$scope', '$location', 'LP', 'AuthService', function($scope, $location, LP, AuthService) {
      $scope.m = LP;
      $scope.showBack = function() {
        return $location.path() !== '/';
      };
      $scope.logout = function() {
        if (confirm("Are you sure?")) {
          AuthService.logout();
          return window.location.href = ".";
        }
      };
      return $scope.isGuest = function() {
        return AuthService.isGuest();
      };
    }
  ]);

}).call(this);
