// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('metaEditor').controller('NavbarCtrl', [
    '$scope', '$location', 'LP', function($scope, $location, LP) {
      $scope.m = LP;
      return $scope.showBack = function() {
        return $location.path() !== '/';
      };
    }
  ]);

}).call(this);
