// Generated by CoffeeScript 1.9.2
(function() {
  angular.module('metaEditor').directive('hoverRow', [
    function() {
      return {
        restrict: 'A',
        link: function(s, e, a) {
          return e.on('click', function() {
            if (!e.hasClass('highlight')) {
              e.parent().children().removeClass('highlight');
              return e.addClass('highlight');
            } else {
              return e.removeClass('highlight');
            }
          });
        }
      };
    }
  ]).directive('ratioEditor', [
    function() {
      return {
        restrict: 'A',
        link: function($scope, $element, $attr) {
          return $element.find('li').on('click', function() {
            var ratioId;
            console.log(this);
            ratioId = $scope.$eval($attr.id);
            return alert(ratioId);
          });
        }
      };
    }
  ]).directive('backButton', [
    function() {
      return {
        restrict: 'E',
        template: '<a ng-click="goBack()" class="back-button" title="Back"><i class="glyphicon glyphicon-2x glyphicon-chevron-left"></i></a>',
        controller: [
          '$scope', '$location', '$window', function($scope, $location, $window) {
            $scope.goBack = function() {
              if ($location.path() !== '/dashboard') {
                return $window.history.back();
              }
            };
            return true;
          }
        ]
      };
    }
  ]);

}).call(this);
