// Generated by CoffeeScript 1.9.2
(function() {
  angular.module('metaEditor').constant('LP', {
    sc: 'Supreme Court',
    ca: 'Court of Appeal',
    fhc: 'Federal High Court',
    tat: 'Tax Appeal Tribunal',
    nic: 'National Industrial Court',
    uk: 'United Kingdom'
  }).factory('AppServe', [
    '$resource', function($resource) {
      return $resource('/api/v1/legalHeads/:_id', null, {
        query: {
          isArray: false
        }
      });
    }
  ]).factory('MergeService', [
    '$http', function($http) {
      var mService;
      mService = {
        url: '/api/v1/',
        mergeSubjectMatters: function(parent, mergeSet, court, legal_head) {
          return $http.post(this.url + 'mergeSubjectMatters', {
            parent: parent,
            mergeSet: mergeSet,
            court: court,
            lh: legal_head
          });
        },
        mergeIssues: function(parent, mergeSet, court, legal_head, subject_matter) {
          return $http.post(this.url + 'mergeIssues', {
            parent: parent,
            mergeSet: mergeSet,
            court: court,
            lh: legal_head,
            sm: subject_matter
          });
        },
        updateSubjectMatter: function(old, newSM, court, legal_head) {
          return $http.post(this.url + 'updateSubjectMatter', {
            old: old,
            "new": newSM,
            court: court,
            lh: legal_head
          });
        },
        updateIssue: function(old, newIssue, court, legal_head, subject_matter) {
          return $http.post(this.url + 'updateIssue', {
            old: old,
            "new": newIssue,
            court: court,
            lh: legal_head,
            sm: subject_matter
          });
        },
        setStandardSM: function(subject_matter, legal_head) {
          return $http.post(this.url + 'setStandard', {
            lh: legal_head,
            sm: subject_matter,
            subject_matter: true
          });
        },
        setStandardIssue: function(issue, subject_matter, legal_head) {
          return $http.post(this.url + 'setStandard', {
            iss: issue,
            lh: legal_head,
            sm: subject_matter,
            issue: true
          });
        },
        changeLegalHead: function(subject_matter, current_legal_head, new_legal_head, court) {
          return $http.post(this.url + 'changeLegalHead', {
            old: current_legal_head,
            "new": new_legal_head,
            sm: subject_matter,
            court: court
          });
        },
        changeSM: function(issue, current_sm, new_sm, legal_head, court) {
          return $http.post(this.url + 'changeSubjectMatter', {
            old: current_sm,
            "new": new_sm,
            issue: issue,
            lh: legal_head,
            court: court
          });
        },
        detachRatio: function(ratio) {
          return $http.post(this.url + 'detachRatio', ratio);
        }
      };
      return mService;
    }
  ]);

}).call(this);
